name: WorkflowEngine Build and Publish to Docker
on: 
  push:
    paths:
    - 'WorkflowEngine/**'
    - '.github/workflows/workflowengine.yml'
  schedule:
    - cron: '0 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Read current version
      id: read_property
      uses: christian-draeger/read-properties@1.0.0
      with:
        path: './WorkflowEngine/VERSION'
        property: 'version'
    - name: Current version
      run: echo ${{ steps.read_property.outputs.value }}
    - name: Bump release version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.0
      with:
        current-version: ${{ steps.read_property.outputs.value }}
        version-fragment: 'bug'
    - name: New version
      run: echo ${{ steps.bump_version.outputs.next-version }}
    - name: Write new version
      uses: christian-draeger/write-properties@1.0.0
      with:
        path: './WorkflowEngine/VERSION'
        property: 'version'
        value: ${{ steps.bump_version.outputs.next-version }}
    - name: Git commit changes version number
      uses: matheusalbino/git-commit@v1.0.1
      with:
          github-token: ${{ secrets.TOKEN }}
          message: 'Updated version to ${{ steps.read_property.outputs.value }}'
    - name: Publish to pkalkman/mve-workflowengine on Docker Hub 
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: pkalkman/mve-workflowengine
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./WorkflowEngine/Dockerfile
        context: ./WorkflowEngine/
        tags: ${{ steps.bump_version.outputs.next-version }}


